* Hyperskip
Hyperskip adds email-powered static comments for Hugo.

** Usage
Insert comment section with
#+BEGIN_SRC html
{{ partial "hyperskip.html" . }}
#+END_SRC

For best compatibility with web feeds like RSS or ATOM, use the following to avoid including =<script>= and =<form>=
#+BEGIN_SRC html
{{ partial "hyperskip_feed.html" . }}
#+END_SRC

The theme expects to find =/data/comments.toml= in the blog directory with the following format:
#+BEGIN_SRC toml
  [[comments]]
  name="Anonymous"
  email_hash="1234abcd8d"
  time=2020-01-01T01:01:01+00:00
  uri="/my-first-post/"
  content="""
  Hello!
  """
  [[comments]]
  name="Ken"
  email_hash="abcd1234h8"
  time=2020-01-01T01:03:01+00:00
  uri="/my-first-post/"
  content="""
  Thanks!
  """
#+END_SRC

For the email form to work properly, please specify in blog's =config.toml= author's email, which will be used for submission and matching blog author's comments. You can specify author information like so:
#+BEGIN_SRC toml
  [author]
  email = "author@example.com"
#+END_SRC

The last 4 characters of =email_hash= will be displayed on the page for anyone aside from the blog author (SHA256 is used to match author email to given email hash). It is preferable to also only store the last few characters of email hash in the =comments.toml= file. This is used as an alternative to services like Gravatar or Libravatar for identification purposes, which would have required storing the entire hash value, an inherent security risk.

By default, form data is sent using URL encoding in body of the email. An easy way to convert it back is to use =urllib.parse.unquote= in Python.
