* Hyperskip
Hyperskip adds email-powered static comments for Hugo.

** Usage
*** Installation
Clone this repository to your themes folder (typically =themes= from Hugo root),
and add Hyperskip to the list of themes (yes, you can use a list of theme names)
in Hugo configuration. Here's an example when using TOML format config
(=config.toml=):
#+BEGIN_SRC toml
theme = ["hugo-djem-so", "hugo-hyperskip"]
#+END_SRC

In template files, insert comment section with
#+BEGIN_SRC html
  {{ partial "hyperskip.html" . }}
#+END_SRC
This would insert both a =mailto= form for comment submissions, and the list of
comments.

For best compatibility with web feeds like RSS or ATOM, use the following to
avoid including =<script>= and =<form>= when inserting comments to web feed
templates
#+BEGIN_SRC html
  {{ partial "hyperskip_feed.html" . }}
#+END_SRC

*** Comment Format
The theme expects to find =data/comments.toml= in Hugo directory with the
following format:
#+BEGIN_SRC toml
  [[comments]]
  name="Anonymous"
  email_hash="1234abcd8d"
  time=2020-01-01T01:01:01+00:00
  uri="/my-first-post/"
  content="""
  Hello!
  """
  [[comments]]
  name="Ken"
  email_hash="abcd1234h8"
  time=2020-01-01T01:03:01+00:00
  uri="/my-first-post/"
  content="""
  Thanks!
  """
#+END_SRC

Due to the linear nature of the way comments are stored, replies are handled by
including an anchor link (or multiple ones) to the comment(s) being replied
to. The structure of comments is thus an directed acyclic graph, instead of a
tree. Anchor links are generated from MD5 hash of author name and timestamp,
both of which are already public information.

For the =mailto= form to work properly, please specify in Hugo configuration
author's email, which will be used for submission and matching blog author's
comments. For example, when using TOML format config (=config.toml=), you can
specify author information like so:
#+BEGIN_SRC toml
  [author]
  email = "author@example.com"
#+END_SRC

The last 4 characters of =email_hash= will be displayed on the page for anyone
aside from the blog author (SHA256 is used to match author email to given email
hash). It is preferable to also only store the last few characters of email hash
in the =comments.toml= file. This is used as an alternative to services like
Gravatar or Libravatar for identification purposes, which would have required
storing the entire hash value, an inherent security risk.

By default, form data is sent using URL encoding in body of the email. An easy
way to convert it back is to use =urllib.parse.unquote= in Python.

*** Webmention
Hyperskip also includes a form for submitting Webmentions. To enable it, specify
Webmention endpoint in your site's =config.toml= (or equivalent) like so:
#+BEGIN_SRC toml
  [params]
  webmentionEndpoint = "https://your-webmention-endpoint/"
#+END_SRC
